# Generated by Django 4.2.2 on 2023-06-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='text',
            field=models.TextField(default='Пустая новость'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(default='Заголовок не задан', max_length=250, verbose_name='title'),
        ),
    ]
